#%RAML 0.8
title: RAML API
version: v1
baseUri: https://api.parse.com/1
schemas:
  - users: !include schemas/usersResponse-schema.json
  - users_1: !include schemas/users_1Request-schema.json
  - users_2: !include schemas/users_2Response-schema.json
  - YPOV1AkiQC: !include schemas/YPOV1AkiQCResponse-schema.json
  - YPOV1AkiQC_1: !include schemas/YPOV1AkiQC_1Request-schema.json
  - YPOV1AkiQC_2: !include schemas/YPOV1AkiQC_2Response-schema.json
  - me: !include schemas/meResponse-schema.json
  - requestPasswordReset: !include schemas/requestPasswordResetRequest-schema.json
/users:
  get:
    responses:
      200:
        body:
          application/json:
            schema: users
            example: !include examples/usersResponse-example.json
  post:
    body:
      application/json:
        schema: users_1
        example: !include examples/users_1Request-example.json
    responses:
      201:
        body:
          application/json:
            schema: users_2
            example: !include examples/users_2Response-example.json
  /YPOV1AkiQC:
    get:
      responses:
        200:
          body:
            application/json:
              schema: YPOV1AkiQC
              example: !include examples/YPOV1AkiQCResponse-example.json
    put:
      body:
        application/json:
          schema: YPOV1AkiQC_1
          example: !include examples/YPOV1AkiQC_1Request-example.json
      responses:
        200:
          body:
            application/json:
              schema: YPOV1AkiQC_2
              example: !include examples/YPOV1AkiQC_2Response-example.json
    delete:
      body:
        application/json:
      responses:
        200:
          body:
            application/json:
  /me:
    get:
      responses:
        200:
          body:
            application/json:
              schema: me
              example: !include examples/meResponse-example.json
/login:
  get:
    queryParameters:
      username:
        example: Test%20User
      password:
        example: testuserpassword
    responses:
      200:
        body:
          application/json:
            schema: me
            example: !include examples/meResponse-example.json
/requestPasswordReset:
  post:
    body:
      application/json:
        schema: requestPasswordReset
        example: !include examples/requestPasswordResetRequest-example.json
    responses:
      200:
        body:
          application/json: